### PR TITLE
Autoconf update

### PR DESCRIPTION
**Pull request by jkroonza**

### CODE REVIEW

**Comment by dfskoll** [comment]
This looks fine.  I wonder if it's time to nuke the gui/ directory and the crufty pppoe-start/pppoe-stop scripts, etc?  They are 20+ years old and I can't believe anyone still uses them.

**Comment by jkroonza** [comment]
Honestly, I *suspect* users of rp-pppoe uses it for it's *server* capabilities (possibly bridge and scan).  ppp project has everything you need for a pppoe client (except a pppoe-scan/discovery tool as far as I'm aware).

We certainly don't use any of the scripts here, only the pppoe-server binary and the rp-pppoe.so plugin for ppp.  Not sure if the ppp project's pppoe.so will work with pppoe-server (obviously some patches or make variables may be required to pppoe-server to actually pass plugin pppoe.so rather than rp-pppoe.so).

As far as GUI stuff goes, if it's not network-manager at this stage, I highly doubt it's being used anywhere.

**Comment by dfskoll** [comment]
OK.  I'll make a separate PR/commit for removing those.  I'll merge this one in the meantime.

**Comment by jkroonza** [comment]
> OK. I'll make a separate PR/commit for removing those. I'll merge this one in the meantime.

I was just about to linearise this for you to avoid the merge commit ... but no harm with the extra commit, it just looks nicer in the history to not have them.

Thank you.

**Pull request merged**
