### PR TITLE
Remote number

### PR DESCRIPTION
**Pull request by jkroonza**

### CODE REVIEW

**Comment by jkroonza** [comment]
Only tested the kernel variant, so please double-check the arguments for user-mode (again, if there are still users of that ... wow).

**Comment by jkroonza** [comment]
Oh wait, what the hell, please don't merge this yet.  Think I got this the wrong way around, but please do advise whether sync should be user-space only mode?

At least that confirms that user-mode still works correctly :).

**Comment by dfskoll** [comment]
On Wed, 14 Dec 2022 06:03:19 -0800
Jaco Kroon ***@***.***> wrote:

> Oh wait, what the hell, please don't merge this yet.  Think I got
> this the wrong way around, but please do advise whether sync should
> be user-space only mode?

sync is only for user-space.  Yeah, I won't merge this one until I pull
it down and test it. :)

Regards,

Dianne.

**Comment by jkroonza** [comment]
yea, I tested without -k ... which is why I thought it was fine.  That was blonde.  Should be sorted now.  sync then remains user-only.  By happy accident I believe I inadvertently tested both user and kernel space, but this is a sensitive change for the merging of the two functions, remotenumber is mundane IMHO.

**Comment by dfskoll** [comment]
OK... since I no longer use rp-pppoe myself, I'm going to have to make a test setup with a couple of (virtual?) machines so I can properly test this.  Might take a few days because $DAY_JOB is rather busy at the moment.

**Comment by Neustradamus** [comment]
@dfskoll: Why not to move this project in a new place to permit the developement?

**Comment by dfskoll** [comment]
On Mon, 02 Jan 2023 13:53:48 -0800
Neustradamus ***@***.***> wrote:

> @dfskoll: Why not to move this project in a new place to permit the
> developement?

@Neustradamus I don't understand what you're asking.  What is wrong
with keeping it on GitHub?

Regards,

Dianne.

**Comment by Neustradamus** [comment]
@dfskoll: Nothing about the repo but you have said "since I no longer use rp-pppoe myself", maybe good to move the project?

**Comment by dfskoll** [comment]
I prefer to keep control over the project... it's my baby. :)

However, I'm more than happy to add other developers to the project.  If you want to be added, please send me a request.

**Comment by jkroonza** [comment]
> I prefer to keep control over the project... it's my baby. :)
>
> However, I'm more than happy to add other developers to the project. If you want to be added, please send me a request.

Do you mind?  I think one requirement should be peer-review or at least two ACKs then.  As it stands your response times are fairly good, however, there are cases like this which is difficult.

**Comment by Neustradamus** [comment]
@jkroonza and @dfskoll: What about this PR on Salsa? ^^
- https://salsa.debian.org/dskoll/rp-pppoe/-/merge_requests/15

Have you looked for the deadline of Debian 12 freeze?
- https://release.debian.org/bookworm/freeze_policy.html

It is important to have the new builds before...

cc: @enaess.

**Comment by dfskoll** [comment]
On Tue, 03 Jan 2023 16:11:29 -0800
Neustradamus ***@***.***> wrote:

> @jkroonza and @dfskoll: What about this PR on Salsa? ^^
> - https://salsa.debian.org/dskoll/rp-pppoe/-/merge_requests/15

I think that one's obsoleted by @jkroonza's control socket mechanism?

> Have you looked for the deadline of Debian 12 freeze?
> - https://release.debian.org/bookworm/freeze_policy.html

I'm working with @enaess on this, but honestly, I'm not going to
attempt to synchronize rp-pppoe releases with Debian releases.  The
next rp-pppoe release will be ready when it's ready, and if that's in
time for the Debian release, that's great... but if not, the existing
rp-pppoe 3.15 is fine for Debian 12.

Regards,

Dianne.

**Comment by jkroonza** [comment]
> On Tue, 03 Jan 2023 16:11:29 -0800 Neustradamus ***@***.***> wrote: @jkroonza and @dfskoll: What about this PR on Salsa? ^^ - https://salsa.debian.org/dskoll/rp-pppoe/-/merge_requests/15
> I think that one's obsoleted by @jkroonza's control socket mechanism?

Correct.  Draining is really the only useful thing that this brings :).

> Have you looked for the deadline of Debian 12 freeze? - https://release.debian.org/bookworm/freeze_policy.html
> I'm working with @enaess on this, but honestly, I'm not going to attempt to synchronize rp-pppoe releases with Debian releases. The next rp-pppoe release will be ready when it's ready, and if that's in time for the Debian release, that's great... but if not, the existing rp-pppoe 3.15 is fine for Debian 12. Regards, Dianne.

I can try to help here, if there are specific issues.  You're welcome to file either PRs or issues and just @ me.

**Pull request merged**
